### ISSUE TITLE
Add Names to Youtube channels

### ISSUE THREAD

**Issue by sakshamgurbhele** [sakshamgurbhele/CP-Resources#1]
## Add names to Links! 😄

Reference: See Image
                  ***👇👇👇👇👇***
![Add names to yt channels](https://user-images.githubusercontent.com/64558515/103411064-1f75f800-4b94-11eb-90c1-16fd34b0bdd7.png)

**Comment by ayushsingh1601** [comment]
I guess this will do good @sakshamgurbhele . 

YouTube Links for helpful Coding Channels :

- [http://tiny.cc/Errichto](url)
- [http://tiny.cc/WilliamLin](url)
- [http://tiny.cc/Pepcoding](url)
- [http://tiny.cc/CodeforCause](url)
- [http://tiny.cc/NickWhite](url)
- [http://tiny.cc/GauravSen](url)
- [http://tiny.cc/RachitJain](url)
- [http://tiny.cc/COPSIITBHU](url)

**Comment by sakshamgurbhele** [comment]
@ayushsingh1601 Yep this looks great! sent a **PR**

**Comment by 96RadhikaJadhav** [comment]
@sakshamgurbhele  Can I work on the issue? I may not be able to make it as @ayushsingh1601 . But I can add in below format and can create a PR if you allow. 
In format as example->  William Lin : https://www.youtube.com/channel/UCKuDLsO0Wwef53qdHPjbU2Q

**Comment by sakshamgurbhele** [comment]
> @sakshamgurbhele Can I work on the issue? I may not be able to make it as @ayushsingh1601 . But I can add in below format and can create a PR if you allow.
> In format as example-> William Lin : https://www.youtube.com/channel/UCKuDLsO0Wwef53qdHPjbU2Q

@96RadhikaJadhav IT WOULD BE BETTER IF YOU CONVERT THOSE LINKS TO SHORT URL. AND BOLD CHANNEL NAMES.
EXAMPLE: **William Lin** : https://tinyurl.com/y54tbf5v

>_IF YOU WISH YOU CAN ADD MORE RELATED CHANNELS TO THE LIST_ 😄

**Comment by 96RadhikaJadhav** [comment]
@sakshamgurbhele  I have created a PR. I've also added some more related channels to the list. Could you please review it and let me know if any other changes required.
