### ISSUE TITLE
Enhancement of Paragraph

### ISSUE THREAD

**Issue by sakshamgurbhele** [sakshamgurbhele/CP-Resources#3]
### Enhance this paragraph

     this isn't looking good

     suggest some ideas    😊

_Feel free to open a PR 🤙_

![Screenshot 2021-01-05 022935](https://user-images.githubusercontent.com/64558515/103579267-f9d35080-4efd-11eb-9c00-c0401c1001f4.png)

**Comment by 96RadhikaJadhav** [comment]
@sakshamgurbhele  Rearranging the above links would do better I guess. To something like:

- https://interviewing.io
- https://www.pramp.com/#/
- https://cp-algorithms.com
- https://cses.fi/problemset/
- https://www.bigocheatsheet.com/
- https://twchen.gitbook.io/leetcode/
- https://petr-mitrichev.blogspot.com
- https://atcoder.jp/contests/dp/tasks
- https://www.hackerearth.com/practice/
- https://www.geeksforgeeks.org/top-10-algorithms-in-interview-questions/
- https://docs.google.com/document/d/1wUCqhVHydWiDk6FJdFLSMpgigNrGcs4OFZg0Wa7JGEw/edit
- https://hackernoon.com/14-patterns-to-ace-any-coding-interview-question-c5bb3357f6ed
- https://leetcode.com/discuss/interview-question/352460/Google-Online-Assessment-Questions
- https://technicalbattle.blogspot.com/2020/05/best-blogs-on-codeforces-links-for-best.html
- https://www.quora.com/What-are-the-best-ways-to-master-dynamic-programming/answer/Sameer-Gulati-3
- https://www.quora.com/How-do-I-get-good-at-math-for-competitive-programming/answer/Sameer-Gulati-3
- https://www.hackerearth.com/blog/developers/7-steps-to-improve-your-data-structure-and-algorithm-skills/
- https://www.quora.com/q/techiedelight/500-Data-Structures-and-Algorithms-interview-questions-and-their-solutions
- https://leetcode.com/discuss/general-discussion/651719/how-to-solve-dp-string-template-and-4-steps-to-be-followed
- https://www.quora.com/What-is-a-list-of-data-structures-that-a-competitive-programmer-must-know/answer/Sameer-Gulati-3?c
- https://www.quora.com/How-can-I-be-good-at-graph-theory-based-programming-problems-in-competitive-programming/answer/Sameer-Gulati-3

**Comment by 96RadhikaJadhav** [comment]
If you feel this is looking better, please let me know. Or if any changes, please suggest. I would like to work on it and create a PR.

**Comment by sakshamgurbhele** [comment]
@96RadhikaJadhav What if Writing briefs or questions and then put links to them? what do you think?

Example: How can I be good at graph theory-based programming problems in competitive programming?
                     https://tinyurl.com/y4g6lx4h

OR
we can create hyperlinks like this in the example!

Example:<a href="https://tinyurl.com/y4g6lx4h"> How can I be good at graph theory based programming problems in competitive programming?</a>

OR

If you have some other suggestions please feel free to let me know

**Comment by 96RadhikaJadhav** [comment]
@sakshamgurbhele  Yeah, hyperlinks looking cool to me! Will work on it and will create a PR soon :) .

**Comment by sakshamgurbhele** [comment]
Cool @96RadhikaJadhav

**Comment by 96RadhikaJadhav** [comment]
@sakshamgurbhele  Created a PR. Could you please review it and let me know if any other changes required.

**Comment by sakshamgurbhele** [comment]
@96RadhikaJadhav It's Great! Thank You🤟
